const GeoInfoActionTypes = {
  SET_NEARBY_RESTAURANTS: "SET_NEARBY_RESTAURANTS",
  SET_CENTER_OF_MAP: "SET_CENTER_OF_MAP",
  SORT_RESTAURANTS_BY_RATING: "SORT_RESTAURANTS_BY_RATING",
  SORT_RESTAURANTS_BY_DISTANCE: "SORT_RESTAURANTS_BY_DISTANCE",
  TOGGLE_RESTAURANT_INFOWINDOW: "TOGGLE_RESTAURANT_INFOWINDOW"
};

export default GeoInfoActionTypes;
